included:


excluded:
- Pods

disabled_rules:
- multiple_closures_with_trailing_closure
- trailing_whitespace

force_cast: warning

identifier_name:
  min_length:
    error: 3
  excluded:
    - y
    - id
